name: "2. Usecase"

on:
  push:
    branches:
      - main
  gollum:

jobs:
  check_mockup_uc_wiki:
    name: "Проверка наличия вики-страницы \"Макет и сценарий использования\" и разделов \"Макет UI\" \"Сценарий использования\" в ней"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check wiki
        with:
          repository: ${{github.repository}}.wiki
      - name: check
        run: |
          page="Макет-и-сценарий-использования.md"
          mockup_header="Макет UI"
          uc_header="Сценарий использования"
         
          if ! [[ -f "${page}" ]]; then 
            echo "::error::Предварительная проверка не пройдена - не найдена вики-страница \"Макет и сценарий использования\""
            exit 1
          fi

          if ! cat "${page}" | grep -q "${mockup_header}"; then 
            echo "::error::Предварительная проверка не пройдена - не найден заголовок ${mockup_header}" 
            exit 1
          fi


          if ! cat "${page}" | grep -q "${uc_header}"; then 
            echo "::error::Предварительная проверка не пройдена - не найден заголовок ${uc_header}" 
            exit 1
          fi

          if ! cat "${page}" | grep -iq "импорт"; then 
            echo "::error::Предварительная проверка не пройдена - не найден сценарий, связанный с импортом данных в систему" 
            exit 1
          fi

          if ! cat "${page}" | grep -iq "экспорт"; then 
            echo "::error::Предварительная проверка не пройдена - не найден сценарий, связанный с экспортом данных в систему" 
            exit 1
          fi

          if ! cat "${page}" | grep -iq "статистик"; then 
            echo "::error::Предварительная проверка не пройдена - не найден сценарий, связанный с подсчетом статистики в системе" 
            exit 1
          fi

          if ! cat "${page}" | grep -iq '](https\:\/\/github.com\/moevm\/[^/]\+\/assets[^\)]\+)'; then 
            echo "::error::Предварительная проверка не пройдена - не найдены изображения макета из репозитория. Вставьте их через \![Название картинки](полная ссылка вида https://github.com/moevm/ВАШ РЕПО/assets/34864759/8f850ef1-fc3d-4adb-a7aa-81598cc7794c) . Если вы храните изображение макета где-то ВНЕ репозитория, то, пожалуйста, разместите файлы в репо - иначе потом очень сложно собирать материалы вашей проекта." 
            exit 1
          fi

          if cat "${page}" | grep 'https\:\/\/' | grep -qv github; then 
            echo "::error::Предварительная проверка не пройдена - найдены ссылки на сторонние сервисы. Если части вашего макета и сценария размещены где-то еще, то, пожалуйста 1) соберите их на вики 2) если у вас сложный макет с figma и тд - положите в репо качественную схему в виде графа. Иначе потом очень сложно собирать материалы вашего проекта." 
            exit 1
          fi          

          echo "::notice::Предварительная проверка пройдена - вики-страница найдена, нужные заголовки присутствуют"
